### ISSUE TITLE
Allow relative path for buildpulse/upload

### ISSUE THREAD

**Issue by tetienne** [Workshop64/buildpulse-circleci-orb#2]
Hi, 

We currently run our tests like this:

```
  - run:
      name: RSpec Tests
      command: bundle exec rspec --format progress --format RspecJunitFormatter --out results/rspec.xml
  - store_test_results:
      path: results/rspec.xml
```

It works fine, the results are well stored within CircleCI. I now want to upload the results to buildpulse.

I’m expecting this to work:
```

- buildpulse/upload:
    path: results/rspec.xml
```

Sadly, I got this error:

```
The given report path is not a directory: results/rspec.xml
To resolve this issue, set the buildpulse/upload 'path' parameter to the directory that contains your test report(s).

Exited with code exit status 1
```

According to the source, the command expect an absolute path. 
```
REPOSITORY_PATH=.
if [ ! -d "$REPOSITORY_PATH" ]
then
  echo "The given repository path is not a directory: ${REPOSITORY_PATH}"
  echo "To resolve this issue, set the buildpulse/upload 'repository-path' parameter to the directory that contains the local git clone of your repository."
  exit 1
fi

```
It would be nice to update it to understand also relative path.
